- hosts: workstation
  tasks:
    - name: Install emacs
      become: true
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - emacs24-nox
        - yaml-mode
        - emacs-goodies-el

    - name: Install Personal Package Preferences
      become: true
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - git
        - htop
        - curl
        - whois
        - mtr
        - python
        - tmux

    - name: Create emacs.d
      file:
        path: '{{ansible_env.HOME}}/.emacs.d'
        state: directory

    - name: Create emacs init file
      template:
        src: files/emacs_init.el
        dest: '{{ansible_env.HOME}}/.emacs.d/init.el'
