- hosts: openstack-hosts
  tasks:
    - name: Add Ubuntu Cloud Keyring
      apt:
        name: ubuntu-cloud-keyring
        state: present

    - name: Add Ubuntu Cloud Archive Newton PPA
      apt_repository:
        repo: "deb http://ubuntu-cloud.archive.canonical.com/ubuntu xenial-updates/newton main"
        state: present

    - name: Add Nova Packages
      apt: update_cache=yes state=present name="{{ item }}"
      with_items:
        - nova-api
        - nova-scheduler
        - nova-conductor
        - nova-consoleauth
        - nova-novncproxy