---
- name: Add Slack Repo GPG key
  apt_key:
    url: "https://packagecloud.io/slacktechnologies/slack/gpgkey"
    state: present

- name: Add Spotify Repo GPG key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: BBEBDCB318AD50EC6865090613B00F1FD2C19886

- name: Add Repos
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - "deb http://repository.spotify.com stable non-free"
    - "deb https://packagecloud.io/slacktechnologies/slack/debian/ jessie main"

- name: Install Desktop Apps
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - spotify-client
    - slack-desktop
    - chromium-browser

